[theme]
theme = "plain"

[icons]
icons = "none"

# 1. CPU usage
[[block]]
block = "cpu"
interval = 5
format = " cpu $utilization "

# 2. CPU temperature
[[block]]
block = "temperature"
interval = 10
format = " temp $max "
chip = "*-isa-*"

# 3. RAM usage
[[block]]
block = "memory"
interval = 5
format = " ram $mem_used_percents "

# 4. Battery
[[block]]
block = "battery"
interval = 20
format = " bat $percentage "

# 5. Brightness
[[block]]
block = "backlight"
device = "intel_backlight"
format = " bri $brightness "

# 5. Uptime
[[block]]
block = "uptime"
interval = 60
format = " $uptime "

# 6. Data and time
[[block]]
block = "time"
interval = 60
format = " $timestamp.datetime(f:'%Y-%m-%d %R')"
